on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.11

    - name: Authenticate do AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1

    - name: Zipping function
      run: zip app.zip app/

    - name: Go to infra directory
      run: cd infra

    - name: Terraform Init
      run: terraform init

    - name: Terraform select Workspace
      run: terraform workspace new ${{ env.ENVIRONMENT }} || terraform workspace select ${{ env.ENVIRONMENT }}
      continue-on-error: true
      env:
        ENVIRONMENT: dev

    - name: Terraform Validate
      run: terraform validate
      env:
        ENVIRONMENT: dev

    - name: Terraform Plan
      run: terraform plan -var-file="./${{ env.ENVIRONMENT }}/env.tfvars"
      env:
        ENVIRONMENT: dev

    - name: Terraform Apply
      run: terraform apply -var-file="./${{ env.ENVIRONMENT }}/env.tfvars" -auto-approve
      env:
        ENVIRONMENT: dev